# Use version 3.8 of the Docker Compose file format.
version: '3.8'

# Define the services, which are essentially the containers to be built and run.
services:
  # The 'client' service represents our C++ application.
  client:
    # Build the image using the Dockerfile in the current directory.
    build: .
    # Define the command to be executed when the container starts. This overrides the Dockerfile's ENTRYPOINT if specified.
    # In this case, we use it to run the compiled client executable.
    command: ./client
    # Map a port from the host machine to the container. This is necessary for a client to connect to a server
    # that is running on the host machine or on another container. In this case, since the client connects to localhost (127.0.0.1)
    # inside the container, we use host networking mode. This allows the container to communicate with services on the host's localhost interface.
    # The 'network_mode: host' configuration is pivotal for this use case.
    network_mode: "host"